
import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'menu.dashboard': 'Dashboard',
    'menu.transactions': 'Transactions',
    'menu.bills': 'Bills & Payables',
    'menu.budget': 'Budget Planner',

    'menu.currency': 'Currency',
    'menu.settings': 'Settings',
    'menu.logout': 'Logout',
    'menu.main': 'MAIN MENU',
    'menu.viewCurr': 'VIEW CURRENCY',
    'menu.savings': 'Piggy Banks',
    'menu.debt': 'Debt Management',
    'menu.about': 'About',

    'header.search': 'Search transactions, bills...',
    'header.notif.empty': 'No pending notifications',
    'header.notif.due': 'due today',
    'header.notif.overdue': 'is overdue',
    'header.notif.soon': 'due soon',

    'dash.title': 'Financial Overview',
    'dash.subtitle': 'Welcome back, check your financial health today.',
    'dash.export': 'Export Report',
    'dash.add': 'Add Transaction',
    'dash.totalBalance': 'Total Balance',
    'dash.income': 'Monthly Income',
    'dash.expenses': 'Monthly Expenses',
    'dash.bills': 'Upcoming Bills',
    'dash.vsLast': 'vs last month',
    'dash.chartTitle': 'Income vs Expenses',
    'dash.recentTrans': 'Recent Transactions',
    'dash.viewAll': 'View All',
    'dash.noTrans': 'No transactions found.',
    'dash.breakdown': 'Expenses Breakdown',
    'dash.topCat': 'Monthly Limits',
    'dash.noBudget': 'No budgets set.',
    'dash.monthTag': 'Month',

    'trans.title': 'Transactions',
    'trans.subtitle': 'Manage your income and expenses.',
    'trans.add': 'Add Transaction',
    'trans.edit': 'Edit Transaction',
    'trans.desc': 'Description',
    'trans.amount': 'Amount',
    'trans.curr': 'Currency',
    'trans.date': 'Date',
    'trans.cat': 'Category',
    'trans.type': 'Type',
    'trans.status': 'Status',
    'trans.pending': 'Pending',
    'trans.completed': 'Completed',
    'trans.actions': 'Actions',
    'trans.income': 'Income',
    'trans.expense': 'Expense',
    'trans.all': 'All',
    'trans.filter': 'Filter by Type',
    'trans.save': 'Save Transaction',
    'trans.cancel': 'Cancel',
    'trans.delete': 'Delete',
    'trans.origCurr': 'Original: ',
    'trans.deleteTitle': 'Delete Transaction',
    'trans.deleteConfirm': 'Are you sure you want to delete this transaction? This action cannot be undone.',
    'trans.confirm': 'Delete',
    'trans.recurring': 'Recurring',
    'trans.newRule': '+ New Rule',
    'trans.noRules': 'No recurring rules set.',
    'trans.next': 'Next:',
    'trans.editRule': 'Edit Rule',
    'trans.freq': 'Frequency',
    'trans.weekly': 'Weekly',
    'trans.monthly': 'Monthly',
    'trans.yearly': 'Yearly',
    'trans.start': 'Start / Next Date',
    'trans.saveRule': 'Save Rule',
    'trans.approx': 'approx',
    'trans.stored': 'stored',
    'trans.searchPlaceholder': 'Search transactions...',

    'bills.title': 'Bills & Payables',
    'bills.subtitle': 'Track your upcoming payments and avoid late fees.',
    'bills.add': 'Add Bill',
    'bills.upcoming': 'Upcoming',
    'bills.paid': 'Paid History',
    'bills.name': 'Bill Name',
    'bills.dueDate': 'Due Date',
    'bills.markPaid': 'Mark as Paid',
    'bills.markUnpaid': 'Mark Unpaid',
    'bills.daysLeft': 'days left',
    'bills.overdue': 'Overdue',
    'bills.today': 'Due Today',
    'bills.category': 'Category',
    'bills.viewList': 'List View',
    'bills.viewCalendar': 'Calendar',
    'bills.enableNotif': 'Enable Reminders',
    'bills.notifEnabled': 'Reminders Active',
    'bills.notifTitle': 'Upcoming Bills Alert',
    'bills.notifBody': 'You have {count} unpaid bills due soon.',
    'bills.totalUnpaid': 'Total Unpaid',
    'bills.nextDue': 'Next Due',
    'bills.paidMonth': 'Paid (This Month)',
    'bills.allCaughtUp': 'All caught up! No upcoming bills.',
    'bills.noPaidHistory': 'No paid history available.',
    'bills.btnToday': 'Today',
    'bills.placeholderName': 'e.g. Netflix Subscription',
    'bills.placeholderCat': 'e.g. Utilities, Entertainment',
    'bills.edit': 'Edit Bill',

    'budget.title': 'Budget Planner',
    'budget.subtitle': 'Plan your monthly spending and track limits.',
    'budget.add': 'Add Category',
    'budget.total': 'Total Budget',
    'budget.spent': 'Spent so far',
    'budget.remaining': 'Remaining',
    'budget.used': 'Used',
    'budget.alert': 'Overspending Alert',
    'budget.alertMsg': 'You have exceeded your allocated budget for',
    'budget.dist': 'Budget Distribution',
    'budget.editLimit': 'Edit Limit',
    'budget.setLimit': 'Set Budget Limit',

    'savings.title': 'Savings & Goals',
    'savings.subtitle': 'Visualize and reach your saving targets',
    'savings.new': 'New Goal',
    'savings.total': 'Total Savings',
    'savings.deposit': 'Deposit',
    'savings.withdraw': 'Withdraw',
    'savings.target': 'Goal',
    'savings.current': 'Current',
    'savings.deadline': 'Deadline',
    'savings.noGoals': 'No savings goals yet.',
    'savings.createFirst': 'Create first goal',
    'savings.edit': 'Edit Goal',
    'savings.name': 'Goal Name',
    'savings.initial': 'Initial Balance',
    'savings.in': 'in',
    'savings.confirm': 'Confirm',
    'savings.cancel': 'Cancel',

    'debt.title': 'Debt Management',
    'debt.subtitle': 'Track loans & credit cards to become debt-free.',
    'debt.add': 'Add Debt',
    'debt.total': 'Total Debt Load',
    'debt.commitments': 'Monthly Commitments',
    'debt.apr': 'APR',
    'debt.progress': 'Progress',
    'debt.paid': 'Paid',
    'debt.remaining': 'Remaining',
    'debt.estPayoff': 'Est. Payoff',
    'debt.noDebts': 'No debts tracked yet. You are free!',
    'debt.edit': 'Edit Debt',
    'debt.name': 'Debt Name',
    'debt.totalLoan': 'Total Loan',
    'debt.minPayment': 'Min. Payment',
    'debt.dueDate': 'Due Date (Day of Month)',
    'debt.update': 'Update Debt',

    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your preferences and categories.',
    'settings.cat': 'Categories',
    'settings.incomeCat': 'Income Categories',
    'settings.expenseCat': 'Expense Categories',
    'settings.addCat': 'Add Category',
    'settings.name': 'Category Name',
    'settings.color': 'Color',
    'settings.create': 'Create Category',
    'settings.danger': 'Danger Zone',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteConfirm': 'Are you sure? This will delete all your data permanently.',
    'settings.enterPassToDelete': 'Enter password to confirm',
    'settings.deleteSuccess': 'Account deleted successfully.',
    'settings.dataManagement': 'Backup & Data',
    'settings.backup': 'Backup Data',
    'settings.backupDesc': 'Save your data to a file',
    'settings.restore': 'Restore Data',
    'settings.restoreDesc': 'Overwrite data from file',
    'settings.backupSuccess': 'Backup created successfully!',
    'settings.restoreSuccess': 'Data restored successfully!',
    'settings.restoreConfirm': 'WARNING: This will overwrite ALL your current data. Are you sure?',

    'cat.salary': 'Salary',
    'cat.freelance': 'Freelance',
    'cat.investments': 'Investments',
    'cat.business': 'Business',
    'cat.gifts': 'Gifts',
    'cat.refunds': 'Refunds',
    'cat.rental': 'Rental Income',
    'cat.housing': 'Housing & Rent',
    'cat.food': 'Food & Dining',
    'cat.transport': 'Transportation',
    'cat.utilities': 'Utilities',
    'cat.insurance': 'Insurance',
    'cat.healthcare': 'Healthcare',
    'cat.education': 'Education',
    'cat.entertainment': 'Entertainment',
    'cat.shopping': 'Shopping',
    'cat.personal': 'Personal Care',
    'cat.travel': 'Travel',
    'cat.debt': 'Debt Payments',
    'cat.pets': 'Pets',
    'cat.kids': 'Kids & Family',
    'cat.subscriptions': 'Subscriptions',

    'curr.title': 'Currency Exchange',
    'curr.subtitle': 'Real-time conversion rates.',
    'curr.amount': 'Amount',
    'curr.from': 'From',
    'curr.to': 'To',
    'curr.calculating': 'Calculating...',
    'curr.marketRate': 'Market Rate',
    'curr.liveRates': 'Live Exchange Rates',
    'curr.base': 'Base Currency',

    'about.title': 'About Aritmo',
    'about.subtitle': 'Meet the developer and see what is coming next.',
    'about.bio': 'pythonist 🐍 :: tool development 📡 :: open source dev 📦 :: data analytics 📊 :: c/c++ & java ☕ :: math enthusiast 📐:🕸️ :: game assets 🎮 :: backend',
    'about.github': 'Visit GitHub',
    'about.roadmap.title': 'Future Improvements',
    'about.imp.cloud': 'Cloud Sync (Optional)',
    'about.imp.cloudDesc': 'Securely sync data across devices.',
    'about.imp.security': 'Advanced Encryption',
    'about.imp.securityDesc': 'Enhanced local data protection.',
    'about.imp.theme': 'Theming Support',
    'about.imp.themeDesc': 'Customizable colors and dark mode toggle.',
    'about.more': '+ More coming soon',
    'about.feedback.title': 'Have Feedback?',
    'about.feedback.desc': 'Your suggestions help shape the future of Aritmo.',
    'about.contact': 'Contact Me',

    'login.welcome': 'Who is looking?',
    'login.welcomeReg': 'Create Profile',
    'login.subtitle': 'Select your profile to enter.',
    'login.description': 'Aritmo is designed to help you take control of your finances securely and offline.',
    'login.subtitleReg': 'Set up your offline profile to get started.',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.btn': 'Enter',
    'login.btnReg': 'Create Profile',
    'login.offline': 'Offline Database Ready',
    'login.error': 'Invalid password.',
    'login.userNotFound': 'User not found.',
    'login.userExists': 'User already exists.',
    'login.createProfile': 'Create Profile',
    'login.selectProfile': 'Select Profile',
    'login.back': 'Back',
    'login.enterPass': 'Enter password for'
  },
  es: {
    'menu.dashboard': 'Panel Principal',
    'menu.transactions': 'Transacciones',
    'menu.bills': 'Cuentas por Pagar',
    'menu.budget': 'Presupuesto',

    'menu.currency': 'Divisas',
    'menu.settings': 'Configuración',
    'menu.logout': 'Cerrar Sesión',
    'menu.main': 'MENÚ PRINCIPAL',
    'menu.viewCurr': 'MONEDA DE VISTA',
    'menu.savings': 'Huchas',
    'menu.debt': 'Gestión de Deudas',
    'menu.about': 'Acerca de',

    'header.search': 'Buscar transacciones, facturas...',
    'header.notif.empty': 'No hay notificaciones pendientes',
    'header.notif.due': 'vence hoy',
    'header.notif.overdue': 'está vencido',
    'header.notif.soon': 'vence pronto',

    'dash.title': 'Resumen Financiero',
    'dash.subtitle': 'Bienvenido, revisa tu salud financiera hoy.',
    'dash.export': 'Exportar Reporte',
    'dash.add': 'Nueva Transacción',
    'dash.totalBalance': 'Balance Total',
    'dash.income': 'Ingresos Mensuales',
    'dash.expenses': 'Gastos Mensuales',
    'dash.bills': 'Pagos Próximos',
    'dash.vsLast': 'vs mes anterior',
    'dash.chartTitle': 'Ingresos vs Gastos',
    'dash.recentTrans': 'Transacciones Recientes',
    'dash.viewAll': 'Ver Todo',
    'dash.noTrans': 'No se encontraron transacciones.',
    'dash.breakdown': 'Desglose de Gastos',
    'dash.topCat': 'Límites Mensuales',
    'dash.noBudget': 'Sin presupuestos.',
    'dash.monthTag': 'Mes',

    'trans.title': 'Transacciones',
    'trans.subtitle': 'Administra tus ingresos y gastos.',
    'trans.add': 'Nueva Transacción',
    'trans.edit': 'Editar Transacción',
    'trans.desc': 'Descripción',
    'trans.amount': 'Monto',
    'trans.curr': 'Moneda',
    'trans.date': 'Fecha',
    'trans.cat': 'Categoría',
    'trans.type': 'Tipo',
    'trans.status': 'Estado',
    'trans.pending': 'Pendiente',
    'trans.completed': 'Completado',
    'trans.actions': 'Acciones',
    'trans.income': 'Ingreso',
    'trans.expense': 'Gasto',
    'trans.all': 'Todos',
    'trans.filter': 'Filtrar por Tipo',
    'trans.save': 'Guardar',
    'trans.cancel': 'Cancelar',
    'trans.delete': 'Eliminar',
    'trans.origCurr': 'Original: ',
    'trans.deleteTitle': 'Eliminar Transacción',
    'trans.deleteConfirm': '¿Estás seguro de que quieres eliminar esta transacción? Esta acción no se puede deshacer.',
    'trans.confirm': 'Eliminar',
    'trans.recurring': 'Recurrentes',
    'trans.newRule': '+ Nueva Regla',
    'trans.noRules': 'No hay reglas recurrentes.',
    'trans.next': 'Siguiente:',
    'trans.editRule': 'Editar Regla',
    'trans.freq': 'Frecuencia',
    'trans.weekly': 'Semanal',
    'trans.monthly': 'Mensual',
    'trans.yearly': 'Anual',
    'trans.start': 'Inicio / Próxima Fecha',
    'trans.saveRule': 'Guardar Regla',
    'trans.approx': 'aprox',
    'trans.stored': 'almacenado',
    'trans.searchPlaceholder': 'Buscar transacciones...',

    'bills.title': 'Cuentas por Pagar',
    'bills.subtitle': 'Rastrea tus próximos pagos y evita recargos.',
    'bills.add': 'Agregar Cuenta',
    'bills.upcoming': 'Próximos',
    'bills.paid': 'Historial de Pagos',
    'bills.name': 'Nombre de Cuenta',
    'bills.dueDate': 'Vencimiento',
    'bills.markPaid': 'Marcar Pagado',
    'bills.markUnpaid': 'Marcar No Pagado',
    'bills.daysLeft': 'días restantes',
    'bills.overdue': 'Vencido',
    'bills.today': 'Vence Hoy',
    'bills.category': 'Categoría',
    'bills.viewList': 'Vista Lista',
    'bills.viewCalendar': 'Calendario',
    'bills.enableNotif': 'Activar Recordatorios',
    'bills.notifEnabled': 'Recordatorios Activos',
    'bills.notifTitle': 'Alerta de Cuentas',
    'bills.notifBody': 'Tienes {count} cuentas por pagar pronto.',
    'bills.totalUnpaid': 'Total Por Pagar',
    'bills.nextDue': 'Próximo Vencimiento',
    'bills.paidMonth': 'Pagado (Este Mes)',
    'bills.allCaughtUp': '¡Todo al día! No hay cuentas pendientes.',
    'bills.noPaidHistory': 'No hay historial de pagos.',
    'bills.btnToday': 'Hoy',
    'bills.placeholderName': 'ej. Netflix, Luz',
    'bills.placeholderCat': 'ej. Servicios, Entretenimiento',
    'bills.edit': 'Editar Cuenta',

    'budget.title': 'Planificador de Gastos',
    'budget.subtitle': 'Planifica tus gastos mensuales y límites.',
    'budget.add': 'Nueva Categoría',
    'budget.total': 'Presupuesto Total',
    'budget.spent': 'Gastado hasta ahora',
    'budget.remaining': 'Restante',
    'budget.used': 'Usado',
    'budget.alert': 'Alerta de Gasto',
    'budget.alertMsg': 'Has excedido tu presupuesto asignado para',
    'budget.dist': 'Distribución de Presupuesto',
    'budget.editLimit': 'Editar Límite',
    'budget.setLimit': 'Establecer Límite',

    'savings.title': 'Huchas y Metas',
    'savings.subtitle': 'Visualiza y alcanza tus objetivos de ahorro',
    'savings.new': 'Nueva Meta',
    'savings.total': 'Ahorro Total',
    'savings.deposit': 'Depositar',
    'savings.withdraw': 'Retirar',
    'savings.target': 'Objetivo',
    'savings.current': 'Actual',
    'savings.deadline': 'Fecha Límite',
    'savings.noGoals': 'No tienes metas de ahorro aún.',
    'savings.createFirst': 'Crear primera meta',
    'savings.edit': 'Editar Meta',
    'savings.name': 'Nombre de la Meta',
    'savings.initial': 'Saldo Inicial',
    'savings.in': 'en',
    'savings.confirm': 'Confirmar',
    'savings.cancel': 'Cancelar',

    'debt.title': 'Gestión de Deudas',
    'debt.subtitle': 'Rastrea préstamos y tarjetas para liberarte de deudas.',
    'debt.add': 'Agregar Deuda',
    'debt.total': 'Carga Total de Deuda',
    'debt.commitments': 'Compromisos Mensuales',
    'debt.apr': 'TAE',
    'debt.progress': 'Progreso',
    'debt.paid': 'Pagado',
    'debt.remaining': 'Restante',
    'debt.estPayoff': 'Est. Pago Final',
    'debt.noDebts': 'No hay deudas registradas. ¡Eres libre!',
    'debt.edit': 'Editar Deuda',
    'debt.name': 'Nombre de Deuda',
    'debt.totalLoan': 'Préstamo Total',
    'debt.minPayment': 'Pago Mínimo',
    'debt.dueDate': 'Día de Vencimiento',
    'debt.update': 'Actualizar Deuda',

    'settings.title': 'Configuración',
    'settings.subtitle': 'Administra tus preferencias y categorías.',
    'settings.cat': 'Categorías',
    'settings.incomeCat': 'Categorías de Ingreso',
    'settings.expenseCat': 'Categorías de Gasto',
    'settings.addCat': 'Nueva Categoría',
    'settings.name': 'Nombre de Categoría',
    'settings.color': 'Color',
    'settings.create': 'Crear Categoría',
    'settings.danger': 'Zona de Peligro',
    'settings.deleteAccount': 'Eliminar Cuenta',
    'settings.deleteConfirm': '¿Estás seguro? Esto borrará todos tus datos permanentemente.',
    'settings.enterPassToDelete': 'Ingresa tu contraseña para confirmar',
    'settings.deleteSuccess': 'Cuenta eliminada exitosamente.',
    'settings.dataManagement': 'Respaldo y Datos',
    'settings.backup': 'Crear Respaldo',
    'settings.backupDesc': 'Guarda tus datos en un archivo',
    'settings.restore': 'Restaurar Datos',
    'settings.restoreDesc': 'Sobrescribe datos desde archivo',
    'settings.backupSuccess': '¡Respaldo creado con éxito!',
    'settings.restoreSuccess': '¡Datos restaurados con éxito!',
    'settings.restoreConfirm': 'ADVERTENCIA: Esto sobrescribirá TODOS tus datos actuales. ¿Estás seguro?',

    'cat.salary': 'Salario',
    'cat.freelance': 'Freelance',
    'cat.investments': 'Inversiones',
    'cat.business': 'Negocio',
    'cat.gifts': 'Regalos',
    'cat.refunds': 'Reembolsos',
    'cat.rental': 'Renta',
    'cat.housing': 'Vivienda',
    'cat.food': 'Alimentos',
    'cat.transport': 'Transporte',
    'cat.utilities': 'Servicios',
    'cat.insurance': 'Seguros',
    'cat.healthcare': 'Salud',
    'cat.education': 'Educación',
    'cat.entertainment': 'Entretenimiento',
    'cat.shopping': 'Compras',
    'cat.personal': 'Cuidado Personal',
    'cat.travel': 'Viajes',
    'cat.debt': 'Deudas',
    'cat.pets': 'Mascotas',
    'cat.kids': 'Hijos y Familia',
    'cat.subscriptions': 'Suscripciones',

    'curr.title': 'Cambio de Divisas',
    'curr.subtitle': 'Tasas de conversión en tiempo real.',
    'curr.amount': 'Cantidad',
    'curr.from': 'De',
    'curr.to': 'A',
    'curr.calculating': 'Calculando...',
    'curr.marketRate': 'Tasa de Mercado',
    'curr.liveRates': 'Tasas de Cambio en Vivo',
    'curr.base': 'Moneda Base',

    'about.title': 'Acerca de Aritmo',
    'about.subtitle': 'Conoce al desarrollador y lo que viene.',
    'about.bio': 'pythonist 🐍 :: tool development 📡 :: open source dev 📦 :: data analytics 📊 :: c/c++ & java ☕ :: math enthusiast 📐:🕸️ :: game assets 🎮 :: backend',
    'about.github': 'Visitar GitHub',
    'about.roadmap.title': 'Mejoras Futuras',
    'about.imp.cloud': 'Sincronización en la Nube (Opcional)',
    'about.imp.cloudDesc': 'Sincroniza datos de forma segura entre dispositivos.',
    'about.imp.security': 'Encriptación Avanzada',
    'about.imp.securityDesc': 'Protección de datos locales mejorada.',
    'about.imp.theme': 'Soporte de Temas',
    'about.imp.themeDesc': 'Colores personalizables y modo oscuro.',
    'about.more': '+ Más próximamente',
    'about.feedback.title': '¿Tienes sugerencias?',
    'about.feedback.desc': 'Tus comentarios ayudan a dar forma al futuro de Aritmo.',
    'about.contact': 'Contáctame',

    'login.welcome': '¿Quién eres?',
    'login.welcomeReg': 'Crear Perfil',
    'login.subtitle': 'Selecciona tu perfil para entrar.',
    'login.description': 'Aritmo está diseñado para ayudarte a tomar el control de tus finanzas de forma segura y offline.',
    'login.subtitleReg': 'Configura tu perfil para comenzar.',
    'login.username': 'Usuario',
    'login.password': 'Contraseña',
    'login.btn': 'Entrar',
    'login.btnReg': 'Crear Perfil',
    'login.offline': 'Base de Datos Offline Lista',
    'login.error': 'Contraseña incorrecta.',
    'login.userNotFound': 'Usuario no encontrado.',
    'login.userExists': 'El usuario ya existe.',
    'login.createProfile': 'Crear Perfil',
    'login.selectProfile': 'Seleccionar Perfil',
    'login.back': 'Volver',
    'login.enterPass': 'Ingresa la clave para'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
